---
title: "Resume"
---

Eleanor L. Lindsey

Fort Collins, CO 80521.eleanorllindsey\@gmail.com.(417) 813-3591

## **EDUCATION**

**Colorado State University. Fort Collins, CO August 2022-December 2025**

-   Bachelor of Science, Ecosystem Science and Sustainability

-   Minor in Watershed Science

    -   Warner College of Natural Resources Dean’s List

## **GIS, TECHNOLOGY EXPERIENCE**

**Environmental Technician Intern May 2024-August 2024**

H2E Incorporated, Denver, CO

-   Monitor vegetative growth in areas of reclamation.

-   Conduct storm water inspections and provide weekly reports.

-   Work with ArcGIS Online to map changes to the environment post inspection.

-   Engage in learning about environmental practices within the oil and gas field.

-   Ensure CDPHE and COGCC regulations are being maintained on sites under H2E contract.

## **PROBLEM-SOLVING EXPERIENCE**

**Pack Leader May 2024-August 2022**

A Dogs World South, Littleton, CO

-   Providing a safe environment for both dogs and coworkers.

-   Supervised groups of up to 30 dogs of different sizes and temperaments.

-   Adept at administering oral medication and monitoring health issues.

## **RELEVANT COURSEWORK**

**Limnology**

-   Studying the biology, chemistry, and physics of lakes including limnological methods and tools.

**Ecology**

-   Interrelationships among organisms and their environments using conceptual models and quantitative approaches.

**Introduction to Geospatial Science**

-   Fundamental concepts of geospatial data, including structure, coordinate systems, sources, and principles of map design. Applications and methods for spatial analysis using vector and raster data, and remote sensing techniques.

## **SUSTAINABILITY ACTIVITIES**

-   Society for Ecological Restoration Club. **Fall 2023-Present**

-   Ecosystem Science and Sustainability Club. **Spring 2023-Present**

-   Watershed Field practicum. **Summer 2024**
